
#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() {
    
    uint xCoordinate = gl_GlobalInvocationID.x;
    uint yCoordinate = gl_GlobalInvocationID.y;

    float x = float(xCoordinate);
    float y = float(yCoordinate);

    for (int i = 0; i < 2500; i++) {
        x*=1.0001;
        y*=1.0002;
    }

    // Make sure compiler doesn't optimize away unused variables
    if (x + y < 0.0) x = 0.0;
}